### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'timeout'

### ISSUE THREAD

**Issue by cartal** [YosefLab/scVI#197]
Hi, 

I'm trying to read a .h5ad as described in the documentation

![screen shot 2018-10-01 at 13 19 39](https://user-images.githubusercontent.com/3297906/46288136-b64e4700-c57c-11e8-95e1-4fedcbad76a9.png)

The files was created by loading a bunch of .h5 files from 10X.  I haven't add any annotation to the h5ad object.

When I try to validate the file using the benchmarking script, I got the following error:

![screen shot 2018-10-01 at 13 17 40](https://user-images.githubusercontent.com/3297906/46288203-e5fd4f00-c57c-11e8-94ba-c366c8330911.png)

Any ideas of what's going on?

Thank you!

**Comment by jules-samaran** [comment]
This error is generated because when the AnnDataset instance is created, the filename and save_path you give do not amount to a valid path from the current directory where you are executing the code so it tries to download it from the URL which is a Nonetype object. You should try to make sure that from the directory where the AnnDataset constructor is called, ./save_path+file_name is a valid path and change save_path or file_name if it isn't. Tell me if it works after checking this

**Comment by cartal** [comment]
It did! Thank you!
