### ISSUE TITLE
PendingDeprecationWarning

### ISSUE THREAD

**Issue by jeff-regier** [YosefLab/scVI#209]
```
  /home/jeff/git/scVI/.tox/py36/lib/python3.6/site-packages/numpy/matrixlib/defmatrix.py:68: 
PendingDeprecationWarning: the matrix subclass is not the recommended way to represent matrices or
deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). 
Please adjust your code to use regular ndarray.
```

**Comment by jeff-regier** [comment]
At worst we can probably able to suppress these warnings by requiring an older version of numpy in `setup.py`.

**Comment by jules-samaran** [comment]
@jeff-regier it seems that since numpy v1.15 this deprecationWarning is being raised and the problem is that scipy.sparse still uses the matrix subclass regularly, so yes indeed adding in set_up the requirement numpy<1.15 works but normally having scipy v1.2 would solve this without having to require an older version of numpy (https://github.com/scipy/scipy/pull/8887) however we do not support currently scipy v1.2:
Collecting scipy>=1.2 (from scvi==0.2.2)
  Could not find a version that satisfies the requirement scipy>=1.2 (from scvi==0.2.2) (from versions: 0.8.0, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.17.0, 0.17.1, 0.18.0rc2, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 1.0.0b1, 1.0.0rc1, 1.0.0rc2, 1.0.0, 1.0.1, 1.1.0rc1, 1.1.0)
No matching distribution found for scipy>=1.2 (from scvi==0.2.2)

**Comment by jeff-regier** [comment]
I guess we better require numpy < 1.15 then, if there's no other way to get rid of the warning. It's a pretty bad experience for our users to be buried in warnings.

**Comment by jules-samaran** [comment]
when running tox, the installed version of sklearn is above 0.20 and raises some Future Warnings that don't appear with the version specified in requirements.txt 0.19.1 (hence when travis runs the tests we don't get those warnings). Should we do something about every warning raised by the more recent versions of modules installed when running tox (since tox uses setup requirements which only give a lower bound for the version)?

**Comment by jeff-regier** [comment]
That's more a of grey area, where there are warnings, but users aren't totally buried in warnings. Hmmm....yes, we may as well specify sklearn <= 0.19.1 until the warnings are fixed.

**Comment by jules-samaran** [comment]
I see, right now everything I'm doing is in a python3.6 environment though
