### ISSUE TITLE
Running the unit tests leaves files all over the place

### ISSUE THREAD

**Issue by jeff-regier** [YosefLab/scVI#210]
Currently all the files below get left behind whenever the unit tests run. But the unit test code should delete any files it creates. To use pytest properly, I think we'd want to do something like this: https://docs.pytest.org/en/latest/fixture.html#fixture-finalization-executing-teardown-code

```
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	Cortex_dataset_imputed_values
	Cortex_dataset_latent_space
	Imputation.png
	spatial-comparison.png
	tests/data/10X/b_cells/filtered_gene_bc_matrices/
	tests/data/10X/cd14_monocytes/filtered_gene_bc_matrices/
	tests/data/10X/cd34/filtered_gene_bc_matrices/
	tests/data/10X/cd4_t_helper/filtered_gene_bc_matrices/
	tests/data/10X/cd56_nk/filtered_gene_bc_matrices/
	tests/data/10X/cytotoxic_t/filtered_gene_bc_matrices/
	tests/data/10X/memory_t/filtered_gene_bc_matrices/
	tests/data/10X/naive_cytotoxic/filtered_gene_bc_matrices/
	tests/data/10X/naive_t/filtered_gene_bc_matrices/
	tests/data/10X/neuron_9k/filtered_gene_bc_matrices/
	tests/data/10X/pbmc4k/filtered_gene_bc_matrices/
	tests/data/10X/pbmc8k/filtered_gene_bc_matrices/
	tests/data/10X/regulatory_t/filtered_gene_bc_matrices/
	tests/data/Rep11_MOB_count_matrix-1.tsv
	tests/data/SeqFISH.xlsx
	tests/data/gene_info_pbmc.csv
	tests/data/neuron_9k/
	tests/data/pbmc_metadata.pickle
	zeiler_clustering_dimension_stability.pdf
```

**Comment by jeff-regier** [comment]
It looks like the preferred way to avoid leaving files behind is for the unit tests to write all files they create to a temporary directory created and managed by pytest:
https://docs.pytest.org/en/2.8.7/tmpdir.html

**Comment by jules-samaran** [comment]
@jeff-regier I looked at tmpdir and tmpdir_factory and I was aiming at creating a temporary directory for the whole test session whose path would become the save_path of all dataset instances so that all downloaded and extracted files be contained in this directory that we can delete at the end of the session. However we use save_path to indicate the location of the already downloaded data which is then for example extracted from a zip file and this operation creates additional files which we want to get rid of at the end of the session. In this case, simply changing save_path to the path of the temporary pytest directory would force us to redownload the **real datafiles** since python would not find it already downloaded in the temporary file instead of using the already present local **test files** (which are much smaller). What we could do is to add an argument `temp_test_path` to the `GeneExpressionDataset` instances and modify the code of each of their constructors so that any extraction or download creating a file during the test session is saved at  `temp_test_path`. Or we could move all the tests/data directory to the repo scVI-data, and just redownload the test files entirely at each test session and do everything inside a temporary test file deleted at the end, doing this would necessitate modifying in the tests code the url used to download the data.
To make it short, most of the **test datafiles** are on the scVI repo in tests/data/ and are hence already downloaded and are meant to be always present locally. However, preprocessing these files can create other files which we do not want to keep. Either we can look at each dataset individually and monitor the creation of not versioned files to put them in the pytest temporary directory, or we can stop storing locally the raw or compressed **test datafiles** and put them in a directory in the scVI-data repo so that we do not have to distinguish downloading and extracting and so that we can just at every test session redownload and extract the **test datafiles** inside a temporary pytest directory.

**Comment by jeff-regier** [comment]
A third option is for each unit test to copy the data it needs from `tests/data` to the pytest temporary directory, and the set `save_path` to the temporary directory rather than to `tests/data`. I think that's probably the best option.

The second option -- moving all the data to the scVI-data repo -- has some appeal too, but then we'd need an internet connection to run the unit tests, which isn't ideal, and the test data wouldn't be versioned with the code.

The first option -- adding extra arguments like `temp_test_path` to code in the `src` directory -- isn't desirable because then the unit tests behave differently than the actual runs.

**Comment by jeff-regier** [comment]
I'm not sure what the best way to copy files is. Maybe it would be OK to use shutil.copy2`? There's also this project:
https://pypi.org/project/pytest-datafiles/

Not sure whether it's worth using -- might be overkill.

**Comment by jules-samaran** [comment]
- By adding the `conftest.py` file to the root of the project, we create at the beginning of each training session (which corresponds to a call of pytest) a temporary directory inside of which we copy the content of the test/data directory. Then all the tests are given the path of the temporary pytest directory as an argument so that all extractions or operations creating and leaving additional files are done in this temp directory. The test configurations of the notebooks are overwritten each time to replace the save_path with the path of the temporary directory the this doesn't affect the actual configurations we use outside of tests. At the end of the session this temporary file is deleted.

- I modified one by one the code which was saving figures and plots by making them save files at the location `save_path` which is the path of the temporary pytest directory when we are running tests and which is the `/data` directory when we are running the notebooks for real. 

- I noticed that some datasets used in the tests don't currently have a compressed format in `tests/data/` yet so tests on these force us to download (so it need an internet connection) the whole dataset and run the tests on the whole data instead of a subsampled version that would make tests even faster. I will make a pull request once I've added all these to `tests/data/`

- concerning #213  I don't know how it was first overwritten but it shouldn't happen now and I restored the good version

**Comment by jeff-regier** [comment]
Sounds good!

**Comment by jeff-regier** [comment]
@jules-samaran Is this done on the js/fix210 branch? If so, will you open a PR for it?

**Comment by romain-lopez** [comment]
where are we on this ? can we merge the PR ?

**Comment by jules-samaran** [comment]
I'll make the final adjustments so that we can merge it

**Comment by romain-lopez** [comment]
got it, it would be great to fix all the warning, I still have some on my
master branch
Romain
-----------------------
Romain Lopez
PhD candidate, EECS
UC Berkeley
romain_lopez@berkeley.edu
+1 (650) 422 9703

**Comment by jules-samaran** [comment]
I made sure all methods that save files or plots that are called in the notebooks or the test methods use the save_path argument when they save a file so that it ends up in the temporary file and gets cleaned at the end of the test session
Thank you for pointing this out
