### ISSUE TITLE
AnnData fails in data_loading notebook

### ISSUE THREAD

**Issue by gamazeps** [YosefLab/scVI#265]
Hi all,

There is a problem loading the AnnData in the `data_loading`, if you try running it it will fail.

This is caused because the data is located in `tests/data` and not in `data` (since no url is given in the notebook example), setting the save_path keyword argument fixes the issue, but it does not seem like intended behavior.

Cheers,
Felix

**Comment by jules-samaran** [comment]
Hi Felix,
the file `TM_droplet_mat.h5ad` is located in `tests/data/` because it is only used to test that the AnnDataset class works correctly. Currently in the `data/` directory we don't have any dataset to use with the AnnDataset class. So the class AnnDataset is actually well designed to be used by any user who has already downloaded a file or who knows the url of the file to be downloaded. This being said, it would still be better if the notebook did not raise any error when being run outside of test sessions. Calling 'tests/data'  in this cell of the notebook as the `save_path` argument rather than the variable `save_path` since we want it to use the test file during test sessions but also outside of test sessions would fix this. 
I just want to check that this would work for all users
Thanks for raising that concern

**Comment by gamazeps** [comment]
Hi Jules,

> So the class AnnDataset is actually well designed to be used by any user who has already downloaded a file or who knows the url of the file to be downloaded
yup, it works perfectly :)

My concern was more the fact that I assume that the notebooks are used as "demos", and it was a bit odd that only this class failed in the demo (even though it worked as intended).
I had to do a bit of digging to find out why it failed and assumed that my installation was incorrect, adding a small line saying to change the `save_path` argument needs to be set to `tests/data` would probably make things clearer.

Cheers,
Felix

**Comment by romain-lopez** [comment]
Hi Felix, 

Thanks for pointing this
I will take some time to go through the notebooks and correct this!
