### ISSUE TITLE
tnse gene visualization

### ISSUE THREAD

**Issue by coh-racng** [YosefLab/scVI#267]
The following snippet adapted from the `scvi.inference.posterior.show_t_sne` plots a tsne representation of subsampled dataset. 

```
latent, batch_indices, labels = trainer.train_set.get_latent(sample=True)
latent, idx_t_sne = trainer.train_set.apply_t_sne(latent, n_samples)
batch_indices = batch_indices[idx_t_sne].ravel()
labels = labels[idx_t_sne].ravel()
plt.scatter(latent[:, 0], latent[:, 1])
```

Currently `show_t_sne` only has the option to color by batches and/or labels. Is there a way to color by normalized gene expression or by ![equation](
https://latex.codecogs.com/gif.latex?%5Crho_g%5En%20%3D%20f_w%5Eg%28z_n%2C%20s_n%29)?
It would be very useful for visualizing datasets that do not already have cell type labels. 

The `get_latent` function loops through the tensors to get the latent representation. How does one loop through the tensors to get the normalized gene expression values or ![equation](
https://latex.codecogs.com/gif.latex?f_w%5Eg%28z_n%2C%20s_n%29)? So that we can color the scatter plot by passing it in as an argument like 
```plt.scatter(latent[:, 0], latent[:, 1], c=gene_value)```

**Comment by jules-samaran** [comment]
Hi Rachel, thank you for raising your concern, the method `trainer.get_latent_and_imputed_values()`  loops through the tensors to provide the latent representation, the imputed values and the normalized imputed values (which you are interested in) for all cells (whereas using the methods with train_set only treats a subsampled part of the dataset). This is shown in the `Obtaining the imputed values for the whole dataset after the training` section of the `basic_tutorial` notebook . In this notebook it is also explained how to obtain the latent representation of all cells rather than just the ones sampled in `train_set`. 
After recovering these you can compute the TSNE transformation of the latent representation of the cells and color the scatter plot with the normalized gene expression level by doing:
```
dic = trainer.get_latent_and_imputed_values()
latent, normalized_gene_value = dic["latent"], dic["scaled_imputed_values"]
tsne_latent, idx_tsne = trainer.train_set.apply_tsne(latent)
plt.scatter(tsne_latent[:, 0], tsne_latent[:, 1], c=normalized_gene_value[idx_tsne])
```
PS: apply_tsne won't use trainer.train_set, it is a static method so it will use the latent representation of all cells that we give it as an argument.
