### ISSUE TITLE
switch from print to logging

### ISSUE THREAD

**Issue by jeff-regier** [YosefLab/scVI#300]
It'd be good to switch the remaining print statements in scVI to calls to `logging`. We have a mix of calls to logging and print currently.

https://docs.python-guide.org/writing/logging/

**Comment by gabmis** [comment]
@jeff-regier  Since I have a verbose parameter for #299 I was looking into this a bit.
It seems that for now we don't call logging. What we have is a `verbose` parameter (per function/method) which is used as follows:
```
if verbose:
    print(...)
```
Do you have a specific suggestion on how to replace those with calls to `logging`?

**Comment by jeff-regier** [comment]
HI Gabriel, Thanks for working on it. These kinds of messages should be either debug-level (`Logging.debug`) or info-level (`Logging.info`). I'm glad if you decide which to use for each message. debug-level is probably better to use for lines that are printed often.
