### ISSUE TITLE
KL Weight (deterministic warmup)

### ISSUE THREAD

**Issue by adamgayoso** [YosefLab/scVI#307]
The KL weight warmup of `self.epoch/400` might be too slow to converge to the ELBO.

https://github.com/YosefLab/scVI/blob/e27cb81812e7bff1b8dfa3624292c353dfbcda96/scvi/inference/inference.py#L50

**Comment by jeff-regier** [comment]
It seems bad to hard code 400 epochs because the size of datasets varies so greatly. It may be better for the warm up to last for a fixed number of iterations (optimization steps) rather than a fixed number of epochs.

Also, I don't think we'd want early stopping ever before the warm up is over. @oscarclivio @PierreBoyeau Perhaps this has something to do with why you're seeing better results with early stopping disabled?

Is  warm up even necessary for good results? I know it seemed like it was at one point, but perhaps other changes we've made make it no longer necessary? 

If it is necessary, perhaps @gabmis would add it to the set of hyperparameters that scVI sets automatically with hyperopt?

**Comment by adamgayoso** [comment]
Are there any updates on this? It seems many of us have been using no deterministic warmup recently. Should we provide a better way to access how long the warmup lasts?

**Comment by romain-lopez** [comment]
We might want to document this better and access the warmup parameter / provide a better way to input the warmup schedule ?

**Comment by jeff-regier** [comment]
How about changing the default behavior to be "no warm up" ? Would that lead to a better or worse user experience? I see benefits/drawbacks to both ways.
