### ISSUE TITLE
One vs all DE bug?

### ISSUE THREAD

**Issue by adamgayoso** [YosefLab/scVI#342]
https://github.com/YosefLab/scVI/blob/336aeb0b1566717aea436b6837c48bd162b4d307/scvi/inference/posterior.py#L295

It's hard for me to tell if this is a bug, in particular, I believe `sample_pairs` should be True, otherwise it's not necessary to report permuted Bayes factors in this function. As an aside, it would be great if someone added docstrings to all DE functions :)

**Comment by jeff-regier** [comment]
^ @romain-lopez

**Comment by romain-lopez** [comment]
sample_pairs=False means that you do not subsample the pairs. I did not write any of the code in this section and it is extremely hard for me to write a docstring. 

There are several open question to designing the API for the differential expression, notably:
- Do we subsample the cells / from the variational distribution. For efficiency, we may need the first and for accuracy we might need the second. how many times then ?
- Do we use importance sampling ? If yes, the code has to be substantially refactored. I partially did it in the scANVI paper repository, but there would be more work to put it in here and I am not sure yet we have a problem with our vanilla estimator.
- What kind of high-level test do we want to perform ? One-VS-All, One-VS-One, etc...
- How to perform DE with multiple batches, with scVI and scANVI ? A lot of code for this is on this repo and the scANVI repo, but there would be some refactorization to perform in order to make it readable. The multiple batches scenario is when the API really needs to be designed well. 
- Is the permutation test really informative or meaningful ? It was more of a sanity check when we wrote the scVI paper and I am not even sure it can be meaningfully used to assign a frequentist p-value for differential expression. If this is the case, might as well get rid of this code. 
- Do we want to reweight the rho values by the ZI weight for example ?

I was hoping we would get some partial answers from the work of Pierre and that would help us move forward on having a functional code for differential expression.

**Comment by jeff-regier** [comment]
Thanks for the information about `sample_pairs`.

@PierreBoyeau It'd be great if you'd think about the issues Adam and Romain have raised. I'm not sure how many of the old DE functions you'll want to keep, but for those we do keep, it'd be good to docstrings.

**Comment by PierreBoyeau** [comment]
Hey everyone,
For sure I will think about that. I can add docstrings but I think that refactoring right now could be a good idea.
@romain-lopez even if your scANVI implementation do not include all old DE functionalities, I think your new implementation is much clearer than before.
As a matter of fact I was working on refactoring the pipeline Friday based on your code. The idea would be to have a cleaner code, optional importance sampling, while keeping the same default behavior for DE.

What do you think?

**Comment by romain-lopez** [comment]
yes that could be helpful !

**Comment by PierreBoyeau** [comment]
Please let me know if you think I should not include importance sampling, if I should include gamma sampling later, if you have other remarks ...

**Comment by romain-lopez** [comment]
It seems to me like importance sampling can wait as well as the gamma
sampling as we do not even know whether this is needed / useful.

**Comment by jeff-regier** [comment]
Seems like Adam was just asking for some better docstrings. We can merge those first and close this issue. After that you may want to focus on importance sampling

**Comment by adamgayoso** [comment]
Yes docstrings would be great! Also the confusion started here:

https://github.com/YosefLab/scVI/blob/master/tests/notebooks/basic_tutorial.ipynb

When `one_vs_all_degenes` is called you get the full table with BF and permuted BF, but it's my understanding that since `sample_pairs` is `False` that these should all have the same value. At least that's what happened when I ran it myself.

**Comment by PierreBoyeau** [comment]
Hey Adam,

I updated the docstrings, feel free to tell me if you think they are clear enough.
I agree with you on this, I added a `sample_pairs` parameter to this method by default at False, I think this cannot hurt
