### ISSUE TITLE
autotune: for multiprocessing, Windows only 'spawn' is available and there is no 'fork' methods.

### ISSUE THREAD

**Issue by zacharylau10** [YosefLab/scVI#350]

**Comment by jeff-regier** [comment]
Does scVI work on Windows otherwise? I've only been testing it with Linux and os x. If replacing fork with spawn is all it takes to support windows, I'm all for it!

**Comment by gabmis** [comment]
Hi @zacharylau10  thank you for pointing this out. 
Although the rest of the repo might be platform agnostic, this code wasn't build to be Windows compatible and this was the expected behaviour. 
Unfortunately, @jeff-regier It's not as simple as that bc forking and spawning a process are two different things. Still, I'll look into it when I have time and if it's an easy fix I'll make it happen. 
In the meantime, @zacharylau10, feel free to submit a PR if you feel like it.

**Comment by jeff-regier** [comment]
The first answer here seem to suggest that the `multiprocessing` module should work on all platforms:
    https://stackoverflow.com/questions/23397/whats-the-best-way-to-duplicate-fork-in-windows

Is that answer wrong, or not applicable to us?

The second answer suggests that fork works under Cygwin, so perhaps that's a workaround in the meantime?

**Comment by jeff-regier** [comment]
This .travis-ci file appears to show how to get travis to test Python code on Windows too:
   https://github.com/kangwonlee/travis-yml-conda-posix-nt/blob/master/.travis.yml
