### ISSUE TITLE
Incorrect MC estimator for marginal log likelihood?

### ISSUE THREAD

**Issue by adamgayoso** [YosefLab/scVI#369]
https://github.com/YosefLab/scVI/blob/7dc873dca0ccfc0f47224f3fee9357e81c0a15eb/scvi/models/log_likelihood.py#L48

Looking at this function it appears to be slightly incorrect as p_x_z contains the KL terms for the library (see return of VAE forward) and furthermore we do not sample the library latent variable.

**Comment by romain-lopez** [comment]
This leaves a tighter lower bound on the likelihood (importance sampling on z and lower bound on l) but is still incorrect I agree. 

1) Instead of using a combination of get_latent and vae, I suggest to call vae.inference on the tensors (make sure to not log the data several times) vae.inference will give you access to the z, the l, and all the parameters. 
2) from this call, you can compute the reconstruction loss using  self._reconstruction_loss. This avoids changing all the API with the differents KL etc.. This reconstruction loss is exactly - log p(x | z, l). (check the sign)
3) Then you need log p(z) and log p(l) as in scvi/models/log_likelihood.py#L69. The prior on l is defined in https://github.com/YosefLab/scVI/blob/master/scvi/models/vae.py#L211
4) Then you need log q(z | x) and log q(l | x). All that comes out of the inference and can be calculated using the formula as in https://github.com/YosefLab/scVI/blob/7dc873dca0ccfc0f47224f3fee9357e81c0a15eb/scvi/models/log_likelihood.py#L71
5) Finally, update the fomula from 
> to_sum[:, i] = p_z + p_x_z - q_z_x 
to 
> to_sum[:, i] = p_z + p_l + p_x_z - q_z_x - q_l_x

**Comment by oscarclivio** [comment]
https://github.com/YosefLab/scVI/blob/7dc873dca0ccfc0f47224f3fee9357e81c0a15eb/scvi/models/log_likelihood.py#L31

This function also uses VAE forward to compute the reconstruction loss, hence includes the KL terms for the library in it.

**Comment by jeff-regier** [comment]
Fixed in #370
