### ISSUE TITLE
How to use 'metrics to monitor'

### ISSUE THREAD

**Issue by AnthoOzier** [YosefLab/scVI#403]
Hello, 

I would like to monitor separately the reconstruction loss and the KL divergence terms during training. I tried to put ['ll','marginal_ll'] as an input of the parameter metrics_to_monitor of my  UnsupervisedTrainer but it didn't work. I only have two lists in my trainer.history that are 'll_train_set' and 'll_test_set'. 
What did I do wrong ?
Is it possible to design my own metric and monitor it during training? 

Thanks

**Comment by ANazaret** [comment]
Hi AnthoOzier,
Thank you for your interest in scVI!

It seems that your problem is a consequence of issue #361, which has been fixed in #358. However, the last changes are not yet released in official repos so you need to install the latest version of scvi directly from our GitHub repo with
`pip install -e git+https://github.com/YosefLab/scVI.git` 

If you don't want to update the whole package for now, here's a workaround tip that should work:
`
trainer._posteriors['train_set'].to_monitor = ['ll','marginal_ll']
trainer._posteriors['test_set'].to_monitor = ['ll','marginal_ll']
`

Note: In the new versions, `ll` is now replaced by `elbo` 

Best, 
Achille
