### ISSUE TITLE
scVI 0.4.1 requires sklearn 0.21

### ISSUE THREAD

**Issue by Munfred** [YosefLab/scVI#452]
When importing scVI (as below) with sklearn 0.20.0 installed I got the error `ImportError: cannot import name '_get_n_jobs'`

The solution was to upgrade to sklearn version 0.21.3, so the scVI requirements should be updated.

Import statement:
```
from scvi.inference import UnsupervisedTrainer
from scvi.inference.posterior import Posterior
```
Error message:
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-9-9cec25c261a2> in <module>()
     13 from scvi.dataset import GeneExpressionDataset
     14 from scvi.models import VAE
---> 15 from scvi.inference import UnsupervisedTrainer
     16 from scvi.inference.posterior import Posterior

~/.local/lib/python3.6/site-packages/scvi/inference/__init__.py in <module>()
----> 1 from .posterior import Posterior
      2 from .trainer import Trainer
      3 from .inference import UnsupervisedTrainer, AdapterTrainer
      4 from .annotation import (
      5     JointSemiSupervisedTrainer,

~/.local/lib/python3.6/site-packages/scvi/inference/posterior.py in <module>()
     13 from matplotlib import pyplot as plt
     14 from scipy.stats import kde, entropy
---> 15 from sklearn.cluster import KMeans
     16 from sklearn.manifold import TSNE
     17 from sklearn.metrics import adjusted_rand_score as ARI

~/.local/lib/python3.6/site-packages/sklearn/cluster/__init__.py in <module>()
      4 """
      5 
----> 6 from .spectral import spectral_clustering, SpectralClustering
      7 from .mean_shift_ import (mean_shift, MeanShift,
      8                           estimate_bandwidth, get_bin_seeds)

~/.local/lib/python3.6/site-packages/sklearn/cluster/spectral.py in <module>()
     15 from ..metrics.pairwise import pairwise_kernels
     16 from ..neighbors import kneighbors_graph
---> 17 from ..manifold import spectral_embedding
     18 from .k_means_ import k_means
     19 

~/.local/lib/python3.6/site-packages/sklearn/manifold/__init__.py in <module>()
      4 
      5 from .locally_linear import locally_linear_embedding, LocallyLinearEmbedding
----> 6 from .isomap import Isomap
      7 from .mds import MDS, smacof
      8 from .spectral_embedding_ import SpectralEmbedding, spectral_embedding

~/.local/lib/python3.6/site-packages/sklearn/manifold/isomap.py in <module>()
      9 from ..utils import check_array
     10 from ..utils.graph import graph_shortest_path
---> 11 from ..decomposition import KernelPCA
     12 from ..preprocessing import KernelCenterer
     13 

~/.local/lib/python3.6/site-packages/sklearn/decomposition/__init__.py in <module>()
      9 from .incremental_pca import IncrementalPCA
     10 from .kernel_pca import KernelPCA
---> 11 from .sparse_pca import SparsePCA, MiniBatchSparsePCA
     12 from .truncated_svd import TruncatedSVD
     13 from .fastica_ import FastICA, fastica

~/.local/lib/python3.6/site-packages/sklearn/decomposition/sparse_pca.py in <module>()
      9 from ..utils import check_random_state, check_array
     10 from ..utils.validation import check_is_fitted
---> 11 from ..linear_model import ridge_regression
     12 from ..base import BaseEstimator, TransformerMixin
     13 from .dict_learning import dict_learning, dict_learning_online

~/.local/lib/python3.6/site-packages/sklearn/linear_model/__init__.py in <module>()
     36 
     37 from .ransac import RANSACRegressor
---> 38 from .theil_sen import TheilSenRegressor
     39 
     40 __all__ = ['ARDRegression',

~/.local/lib/python3.6/site-packages/sklearn/linear_model/theil_sen.py in <module>()
     21 from ..base import RegressorMixin
     22 from ..utils import check_random_state
---> 23 from ..utils import check_X_y, _get_n_jobs
     24 from ..externals.joblib import Parallel, delayed
     25 from ..externals.six.moves import xrange as range

ImportError: cannot import name '_get_n_jobs'
```

**Comment by gokceneraslan** [comment]
Is there any reason to pin the versions of ALL required packages?

https://github.com/YosefLab/scVI/blob/master/requirements.txt:

```
pip==18.1
flake8==3.7.7
coverage==4.5.1
Sphinx==1.7.1
pytest==3.7.4
pytest-runner==2.11.1
numpy==1.16.2
torch==1.0.1
matplotlib==3.0.3
scikit-learn==0.20.3
scipy==1.2.1
h5py==2.9.0
codecov==2.0.8
pandas==0.24.2
loompy==2.0.16
tqdm==4.31.1
anndata==0.6.18
xlrd==1.2.0
nbconvert==5.4.0
nbformat==4.4.0
jupyter==1.0.0
ipython==7.1.1
umap-learn==0.3.8
seaborn==0.9.0
leidenalg==0.7.0
numba==0.45.0
python-igraph==0.7.1.post6
scanpy==1.4
louvain==0.6.1
hyperopt==0.1.2
black==19.3b0
colour==0.1.5
```

**Comment by jeff-regier** [comment]
@gokceneraslan We're just storing a list of packages in `requirements.txt` that works on travis-ci. The package requirements appear here, in setup.py.

@romain-lopez @gabmis Do you recall why we're disallowing sklearn later than 0.20 in `setup.py`? Also, how is it that our unit tests pass on travis-ci with sklearn 0.20.3 yet @Munfred is getting there error above?

**Comment by gokceneraslan** [comment]
@jeff-regier I makes more sense to unify requirements.txt and the dependencies defined in setup.py in order to make travis environment more similar to what users' environment. Also, `< version` constraint is typically very harsh since it will always downgrade both numba and scikit-learn. It'd be great if you can pinpoint the problematic versions and use something more permissive e.g. `!= version`.

**Comment by jeff-regier** [comment]
I can see the case for both ways -- for us it's problematic when unit tests fail on travis-ci due to changes to third party libraries, rather than due to changes to our code. On other hand, having multiple lists of dependencies is pretty unwieldy too (we also maintain a list of conda dependencies in the bioconda repository). Lately we're spending a lot of time struggling with dependency versions. I'd like to find a better way.

With that in mind, unifying `requirements.txt` and `setup.py` seems worth it to me, as well as doing away with pinned versions. I like the idea of using `!= version` syntax.

**Comment by romain-lopez** [comment]
Hi everyone, 

+ I cannot remember exactly why we prohibited some version of sklearn. 
+ I know numba is restricted because of a new version released on August 2nd that makes UMAP fail. This breaks our unit tests.

The requirements are indeed a huge pain and there is a certain overhead to maintaining bioconda, travis as well as setup.py. 

Is there a decent way to merge the three of them ?

For requirements.txt and setup.py I like our philosophy that we do not want travis to fail just because of a new repo. Especially, we have two configurations in tox which tests the travis build as well as the setup.py file. 

The priorities to me are then:
1. make the requirements from bioconda overlap with setup.py. This is particularly tedious because of the extra packages we have in the optional dependencies (igraph etc...)
2.  make sure we do not use a < version syntaxt 
3. trying to remove requirements.txt

Any suggestions on how to move forward with that ?

**Comment by gabmis** [comment]
I agree with @gokceneraslan and @jeff-regier and as I have said in the past am in favour of unifying our dependecy list into a unique one.

1. we'd just need to remove the `--no-deps` flag in our bioconda recipe, and delete the explicit requirements

https://github.com/bioconda/bioconda-recipes/blob/2ee08b33c4347248e86fc5ba3232577cf04d729b/recipes/scvi/meta.yaml#L18

2. Take a closer look at our setup.py and translate the remaining uses of the "<" syntax.

3. remove requirements.txt and fix any resulting incompatibility

**Comment by PierreBoyeau** [comment]
I think that for `sklearn>=0.21`, `train_test_split` does not accept `train_size=1.0` anymore, causing some tests to fail. 
I don't know if this is the reason why we prohibit more recent versions of scikit-learn, but I think we will have to deal with that issue at some point.

**Comment by jeff-regier** [comment]
Seems relevant: https://realpython.com/pipenv-guide/

**Comment by adamgayoso** [comment]
Alternatively, we could structure our package like is done in scanpy:

https://github.com/theislab/scanpy

They have a requirements.txt that is parsed in setup.py
